# Eureka configuration
eureka:
  # Configuration for this Eureka instance
  instance:
    hostname: localhost  # Sets the hostname of this Eureka instance (for local development)
  client:
    # Points to the Eureka server at localhost:8761
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Server configuration
server:
  port: 8081  # Sets the port number for the application server

# Spring application configuration
spring:
  application:
    name: school  # Sets the application name to 'student'

  # Configuration management using Spring Cloud Config
  config:
    import: optional:configserver:http://localhost:8888  # Imports configuration from a Spring Cloud Config Server

  # Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver class
    url: jdbc:mysql://localhost:3306/school  # MySQL database URL
    username: root  # Database username
    password: root  # Database password


  jpa:
    hibernate:
      ddl-auto: update  # Hibernate schema update mode
    database: mysql  # Database type